#!/usr/bin/python3

# Generated by Django 3.2.15 on 2023-01-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistsAlbums',
            fields=[
                ('artists_albums_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'artists_albums',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='AlbumsArtists',
        ),
    ]
