# Generated by Django 3.2.15 on 2023-01-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20230107_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistsGenres',
            fields=[
                ('artists_genres_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'artists_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArtistsSongs',
            fields=[
                ('artists_songs_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'artists_songs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerAccounts',
            fields=[
                ('buyer_id', models.AutoField(primary_key=True, serialize=False, verbose_name='buyer ID')),
                ('storefront_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='storefront name')),
                ('date_created', models.DateField(verbose_name='date created')),
            ],
            options={
                'db_table': 'buyer_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SellerAccounts',
            fields=[
                ('seller_id', models.AutoField(primary_key=True, serialize=False, verbose_name='seller ID')),
                ('postboard_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='postboard name')),
                ('date_created', models.DateField(verbose_name='date created')),
            ],
            options={
                'db_table': 'seller_accounts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SongsGenres',
            fields=[
                ('songs_genres_id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'songs_genres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToBuyListings',
            fields=[
                ('to_buy_listing_id', models.AutoField(primary_key=True, serialize=False, verbose_name='to-buy listing ID')),
                ('max_accepting_price', models.DecimalField(decimal_places=65535, max_digits=65535, verbose_name='maximum price to accept')),
                ('date_posted', models.DateField(blank=True, null=True, verbose_name='date posted')),
            ],
            options={
                'db_table': 'to_buy_listings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ToSellListings',
            fields=[
                ('to_sell_listing_id', models.AutoField(primary_key=True, serialize=False, verbose_name='to-sell listing ID')),
                ('asking_price', models.DecimalField(decimal_places=65535, max_digits=65535, verbose_name='asking price')),
                ('date_posted', models.DateField(blank=True, null=True, verbose_name='date posted')),
            ],
            options={
                'db_table': 'to_sell_listings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPasswords',
            fields=[
                ('password_id', models.AutoField(primary_key=True, serialize=False, verbose_name='password ID')),
                ('password_ciphertext', models.CharField(max_length=256, verbose_name='password ciphertext')),
            ],
            options={
                'db_table': 'user_passwords',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, verbose_name='user ID')),
                ('user_handle', models.CharField(max_length=16, verbose_name='user handle')),
                ('user_name', models.CharField(max_length=64, verbose_name='user name')),
                ('date_joined', models.DateField(verbose_name='date joined')),
                ('buyer_id', models.IntegerField(blank=True, null=True)),
                ('seller_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
